import {
  RoadSegment,
  Bridge,
  IncidentReport,
  DisruptionPrediction,
  TrackedVehicle,
  AlertNotification,
  DistrictConnectivity,
  RouteOption,
} from '@/types/logistics'

export const INITIAL_ROADS: RoadSegment[] = [
  {
    id: 'road-nh27-kamrup',
    code: 'NH-27-SecA',
    name: 'NH-27 Guwahati – Nagaon Bypass',
    state: 'Assam',
    district: 'Kamrup Metro',
    from: 'Guwahati (Jalukbari)',
    to: 'Nagaon Interlink',
    category: 'national_highway',
    status: 'open',
    riskScore: 18,
    riskLevel: 'low',
    lengthKm: 122,
    conditionScore: 8.5,
    slopeDeg: 8,
    soilMoisturePercent: 42,
    rainfallMmPerHour: 6,
    lastInspection: '2026-09-17 08:30',
    coordinates: [
      [26.1445, 91.7362],
      [26.185, 91.89],
      [26.25, 92.2],
      [26.345, 92.684],
    ],
    activeIncidentsCount: 0,
    hazardType: 'clear',
  },
  {
    id: 'road-nh29-kohima',
    code: 'NH-29-Barail',
    name: 'NH-29 Dimapur – Kohima Mountain Pass',
    state: 'Nagaland',
    district: 'Kohima',
    from: 'Chumoukedima',
    to: 'Kohima Town Gate',
    category: 'national_highway',
    status: 'blocked',
    riskScore: 92,
    riskLevel: 'high',
    lengthKm: 68,
    conditionScore: 3.2,
    slopeDeg: 42,
    soilMoisturePercent: 88,
    rainfallMmPerHour: 48,
    lastInspection: '2026-09-18 09:15',
    coordinates: [
      [25.82, 93.75],
      [25.75, 93.9],
      [25.67, 94.1],
      [25.6751, 94.1086],
    ],
    activeIncidentsCount: 2,
    hazardType: 'landslide',
  },
  {
    id: 'road-nh6-jowai',
    code: 'NH-06-Megh',
    name: 'NH-6 Shillong – Jowai – Ratacherra Corridor',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    from: 'Shillong Bypass',
    to: 'Jowai Cachar Gate',
    category: 'national_highway',
    status: 'at_risk',
    riskScore: 68,
    riskLevel: 'medium',
    lengthKm: 94,
    conditionScore: 5.8,
    slopeDeg: 34,
    soilMoisturePercent: 76,
    rainfallMmPerHour: 32,
    lastInspection: '2026-09-18 11:00',
    coordinates: [
      [25.5788, 91.8933],
      [25.5, 92.05],
      [25.45, 92.21],
      [25.32, 92.38],
    ],
    activeIncidentsCount: 1,
    hazardType: 'road_damage',
  },
  {
    id: 'road-nh10-gangtok',
    code: 'NH-10-Teesta',
    name: 'NH-10 Sevoke – Singtam – Gangtok Lifeline',
    state: 'Sikkim',
    district: 'East Sikkim',
    from: 'Sevoke Kalijhora',
    to: 'Gangtok Deorali',
    category: 'national_highway',
    status: 'at_risk',
    riskScore: 74,
    riskLevel: 'high',
    lengthKm: 114,
    conditionScore: 4.9,
    slopeDeg: 46,
    soilMoisturePercent: 81,
    rainfallMmPerHour: 38,
    lastInspection: '2026-09-18 07:45',
    coordinates: [
      [26.89, 88.47],
      [27.05, 88.52],
      [27.23, 88.58],
      [27.3389, 88.6065],
    ],
    activeIncidentsCount: 1,
    hazardType: 'flood',
  },
  {
    id: 'road-nh102-imphal',
    code: 'NH-102-TransBorder',
    name: 'NH-102 Imphal – Pallel – Moreh Asian Highway',
    state: 'Manipur',
    district: 'Imphal West',
    from: 'Imphal Kangla',
    to: 'Moreh Border Gate',
    category: 'national_highway',
    status: 'open',
    riskScore: 24,
    riskLevel: 'low',
    lengthKm: 108,
    conditionScore: 8.0,
    slopeDeg: 14,
    soilMoisturePercent: 46,
    rainfallMmPerHour: 8,
    lastInspection: '2026-09-17 16:00',
    coordinates: [
      [24.817, 93.9368],
      [24.62, 93.98],
      [24.45, 94.08],
      [24.25, 94.3],
    ],
    activeIncidentsCount: 0,
    hazardType: 'clear',
  },
  {
    id: 'road-nh13-tawang',
    code: 'NH-13-Sela',
    name: 'Trans-Arunachal NH-13 Bhalukpong – Bomdila – Tawang',
    state: 'Arunachal Pradesh',
    district: 'Tawang',
    from: 'Dirang Valley',
    to: 'Tawang High Pass',
    category: 'border_road',
    status: 'at_risk',
    riskScore: 71,
    riskLevel: 'high',
    lengthKm: 185,
    conditionScore: 5.2,
    slopeDeg: 48,
    soilMoisturePercent: 65,
    rainfallMmPerHour: 22,
    lastInspection: '2026-09-18 06:30',
    coordinates: [
      [27.35, 92.24],
      [27.42, 92.12],
      [27.53, 91.95],
      [27.586, 91.866],
    ],
    activeIncidentsCount: 1,
    hazardType: 'landslide',
  },
  {
    id: 'road-nh306-aizawl',
    code: 'NH-306-Vairangte',
    name: 'NH-306 Silchar – Vairangte – Aizawl Lifeline',
    state: 'Mizoram',
    district: 'Aizawl',
    from: 'Silchar Railhead',
    to: 'Aizawl Bawngkawn',
    category: 'national_highway',
    status: 'open',
    riskScore: 32,
    riskLevel: 'low',
    lengthKm: 178,
    conditionScore: 7.1,
    slopeDeg: 28,
    soilMoisturePercent: 54,
    rainfallMmPerHour: 14,
    lastInspection: '2026-09-17 14:15',
    coordinates: [
      [24.83, 92.79],
      [24.45, 92.75],
      [24.08, 92.73],
      [23.7367, 92.7176],
    ],
    activeIncidentsCount: 0,
    hazardType: 'clear',
  },
  {
    id: 'road-nh208-agartala',
    code: 'NH-208-Sabroom',
    name: 'NH-208 Agartala – Udaipur – Sabroom Corridor',
    state: 'Tripura',
    district: 'West Tripura',
    from: 'Agartala Central',
    to: 'Maitri Setu Sabroom',
    category: 'national_highway',
    status: 'open',
    riskScore: 15,
    riskLevel: 'low',
    lengthKm: 130,
    conditionScore: 8.8,
    slopeDeg: 6,
    soilMoisturePercent: 38,
    rainfallMmPerHour: 4,
    lastInspection: '2026-09-18 10:00',
    coordinates: [
      [23.8315, 91.2868],
      [23.53, 91.48],
      [23.3, 91.6],
      [23.01, 91.71],
    ],
    activeIncidentsCount: 0,
    hazardType: 'clear',
  },
]

export const INITIAL_BRIDGES: Bridge[] = [
  {
    id: 'br-bogibeel',
    name: 'Bogibeel Rail-cum-Road Bridge',
    roadCode: 'NH-15 Interlink',
    river: 'Brahmaputra River',
    district: 'Dibrugarh',
    state: 'Assam',
    spanMeters: 4940,
    healthIndexPercent: 94,
    status: 'open',
    lastAuditDate: '2026-09-10',
    coordinates: [27.4, 94.8],
  },
  {
    id: 'br-sadiya',
    name: 'Bhupen Hazarika Setu (Dhola-Sadiya)',
    roadCode: 'NH-115 Ext',
    river: 'Lohit River',
    district: 'Tinsukia',
    state: 'Assam / Arunachal',
    spanMeters: 9150,
    healthIndexPercent: 91,
    status: 'open',
    lastAuditDate: '2026-09-12',
    coordinates: [27.8, 95.6],
  },
  {
    id: 'br-saraighat',
    name: 'Saraighat New River Bridge',
    roadCode: 'NH-27',
    river: 'Brahmaputra River',
    district: 'Kamrup Metro',
    state: 'Assam',
    spanMeters: 1492,
    healthIndexPercent: 88,
    status: 'open',
    lastAuditDate: '2026-09-15',
    coordinates: [26.13, 91.68],
  },
  {
    id: 'br-dzudo',
    name: 'Barail Ravine Bridge No. 4',
    roadCode: 'NH-29-Barail',
    river: 'Chathe Torrent',
    district: 'Kohima',
    state: 'Nagaland',
    spanMeters: 180,
    healthIndexPercent: 41,
    status: 'blocked',
    lastAuditDate: '2026-09-18',
    coordinates: [25.72, 93.95],
  },
  {
    id: 'br-teesta',
    name: 'Teesta River Truss Span Bridge',
    roadCode: 'NH-10-Teesta',
    river: 'Teesta River',
    district: 'East Sikkim',
    state: 'Sikkim',
    spanMeters: 240,
    healthIndexPercent: 62,
    status: 'at_risk',
    lastAuditDate: '2026-09-16',
    coordinates: [27.18, 88.54],
  },
]

export const INITIAL_DISTRICTS: DistrictConnectivity[] = [
  {
    district: 'Kamrup Metro',
    state: 'Assam',
    totalRoadsKm: 840,
    openRoadsKm: 810,
    atRiskRoadsKm: 30,
    blockedRoadsKm: 0,
    connectivityIndexPercent: 96,
    essentialSuppliesBufferDays: { medical: 28, foodGrain: 45, fuelPol: 22 },
    populationServed: 1253000,
  },
  {
    district: 'Kohima',
    state: 'Nagaland',
    totalRoadsKm: 420,
    openRoadsKm: 260,
    atRiskRoadsKm: 92,
    blockedRoadsKm: 68,
    connectivityIndexPercent: 62,
    essentialSuppliesBufferDays: { medical: 6, foodGrain: 12, fuelPol: 5 },
    populationServed: 270000,
    isCriticalDisasterZone: true,
  },
  {
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    totalRoadsKm: 610,
    openRoadsKm: 485,
    atRiskRoadsKm: 94,
    blockedRoadsKm: 31,
    connectivityIndexPercent: 79,
    essentialSuppliesBufferDays: { medical: 14, foodGrain: 20, fuelPol: 11 },
    populationServed: 825000,
  },
  {
    district: 'East Sikkim',
    state: 'Sikkim',
    totalRoadsKm: 380,
    openRoadsKm: 266,
    atRiskRoadsKm: 114,
    blockedRoadsKm: 0,
    connectivityIndexPercent: 70,
    essentialSuppliesBufferDays: { medical: 8, foodGrain: 14, fuelPol: 7 },
    populationServed: 285000,
    isCriticalDisasterZone: true,
  },
  {
    district: 'Tawang',
    state: 'Arunachal Pradesh',
    totalRoadsKm: 320,
    openRoadsKm: 210,
    atRiskRoadsKm: 85,
    blockedRoadsKm: 25,
    connectivityIndexPercent: 65,
    essentialSuppliesBufferDays: { medical: 9, foodGrain: 16, fuelPol: 8 },
    populationServed: 54000,
  },
  {
    district: 'Imphal West',
    state: 'Manipur',
    totalRoadsKm: 510,
    openRoadsKm: 470,
    atRiskRoadsKm: 40,
    blockedRoadsKm: 0,
    connectivityIndexPercent: 92,
    essentialSuppliesBufferDays: { medical: 21, foodGrain: 30, fuelPol: 18 },
    populationServed: 517000,
  },
  {
    district: 'Aizawl',
    state: 'Mizoram',
    totalRoadsKm: 490,
    openRoadsKm: 430,
    atRiskRoadsKm: 60,
    blockedRoadsKm: 0,
    connectivityIndexPercent: 88,
    essentialSuppliesBufferDays: { medical: 19, foodGrain: 26, fuelPol: 15 },
    populationServed: 400000,
  },
  {
    district: 'West Tripura',
    state: 'Tripura',
    totalRoadsKm: 560,
    openRoadsKm: 535,
    atRiskRoadsKm: 25,
    blockedRoadsKm: 0,
    connectivityIndexPercent: 95,
    essentialSuppliesBufferDays: { medical: 25, foodGrain: 38, fuelPol: 20 },
    populationServed: 918000,
  },
]

export const INITIAL_VEHICLES: TrackedVehicle[] = [
  {
    id: 'veh-as01-med',
    plateNumber: 'AS-01-GC-4482',
    driverName: 'Biren Gogoi',
    driverContact: '+91 94350 28114',
    cargoType: 'medical',
    cargoDescription: 'Oxygen cylinders, IV fluids & antibiotics',
    cargoWeightTons: 6.8,
    origin: 'Guwahati Med Depot',
    destination: 'Kohima District Hospital',
    currentDistrict: 'Kohima Approach',
    currentRoadCode: 'NH-29-Barail',
    lat: 25.76,
    lng: 93.88,
    speedKmh: 12,
    status: 'delayed',
    isAtRisk: true,
    riskReason: 'NH-29 Barail Pass blocked by 50m mudslide at KM-42',
    etaMinutes: 240,
    delayMinutes: 95,
    pathPoints: [
      [26.14, 91.73],
      [26.25, 92.5],
      [25.85, 93.75],
      [25.76, 93.88],
    ],
  },
  {
    id: 'veh-mz02-pds',
    plateNumber: 'MZ-01-E-9041',
    driverName: 'Lalmuanpuia Ralte',
    driverContact: '+91 98623 71092',
    cargoType: 'pds_rations',
    cargoDescription: 'FCI Wheat & Rice PDS Supplies (15 MT)',
    cargoWeightTons: 15.0,
    origin: 'Silchar FCI Silo',
    destination: 'Aizawl Civil Supplies Godown',
    currentDistrict: 'Aizawl',
    currentRoadCode: 'NH-306-Vairangte',
    lat: 24.12,
    lng: 92.74,
    speedKmh: 42,
    status: 'in_transit',
    isAtRisk: false,
    etaMinutes: 110,
    delayMinutes: 0,
    pathPoints: [
      [24.83, 92.79],
      [24.45, 92.75],
      [24.12, 92.74],
      [23.73, 92.71],
    ],
  },
  {
    id: 'veh-sk04-pol',
    plateNumber: 'SK-01-D-3180',
    driverName: 'Pemba Lepcha',
    driverContact: '+91 97330 44921',
    cargoType: 'fuel_pol',
    cargoDescription: 'IOCL High Speed Diesel tanker (12,000 L)',
    cargoWeightTons: 11.2,
    origin: 'Siliguri IOCL Terminal',
    destination: 'Gangtok IOCL Retail Depot',
    currentDistrict: 'East Sikkim',
    currentRoadCode: 'NH-10-Teesta',
    lat: 27.15,
    lng: 88.55,
    speedKmh: 24,
    status: 'delayed',
    isAtRisk: true,
    riskReason: 'Teesta River flash-flood alert near Singtam low-causeway',
    etaMinutes: 180,
    delayMinutes: 50,
    pathPoints: [
      [26.89, 88.47],
      [27.05, 88.52],
      [27.15, 88.55],
    ],
  },
  {
    id: 'veh-mn01-relief',
    plateNumber: 'MN-01-AA-6520',
    driverName: 'Thoiba Singh',
    driverContact: '+91 96121 88310',
    cargoType: 'disaster_relief',
    cargoDescription: 'Tarpaulin kits, water purification pills, dry rations',
    cargoWeightTons: 8.5,
    origin: 'Imphal SDRF Depot',
    destination: 'Churachandpur Relief Hub',
    currentDistrict: 'Imphal West',
    currentRoadCode: 'NH-102-TransBorder',
    lat: 24.68,
    lng: 93.95,
    speedKmh: 50,
    status: 'in_transit',
    isAtRisk: false,
    etaMinutes: 45,
    delayMinutes: 0,
    pathPoints: [
      [24.81, 93.93],
      [24.68, 93.95],
    ],
  },
]

export const INITIAL_INCIDENTS: IncidentReport[] = [
  {
    id: 'inc-2026-0918-01',
    reporterId: 'fo-nagaland-42',
    reporterName: 'Inspector Kevichusa',
    reporterRole: 'field_officer',
    timestamp: '2026-09-18 08:52',
    district: 'Kohima',
    roadCode: 'NH-29-Barail',
    incidentType: 'landslide',
    severity: 'critical',
    status: 'verified',
    lat: 25.7512,
    lng: 93.8945,
    elevationMeters: 1430,
    photoUrl: '/images/quantum-nebula.png',
    description: 'Major slope collapse over 65 meters. Both carriageways buried under mud & rock boulders. Heavy earthmovers mobilized.',
  },
  {
    id: 'inc-2026-0918-02',
    reporterId: 'fo-sikkim-11',
    reporterName: 'Sub-Inspector Karma Bhutia',
    reporterRole: 'field_officer',
    timestamp: '2026-09-18 07:15',
    district: 'East Sikkim',
    roadCode: 'NH-10-Teesta',
    incidentType: 'flood',
    severity: 'high',
    status: 'verified',
    lat: 27.182,
    lng: 88.541,
    elevationMeters: 890,
    photoUrl: '/images/quantum-orb.png',
    description: 'Teesta water level breaching safety revetment. One-way light vehicle transit only under SDRF escort.',
  },
  {
    id: 'inc-2026-0918-03',
    reporterId: 'fo-megh-08',
    reporterName: 'Officer Marbaniang',
    reporterRole: 'field_officer',
    timestamp: '2026-09-18 10:10',
    district: 'East Khasi Hills',
    roadCode: 'NH-06-Megh',
    incidentType: 'road_damage',
    severity: 'medium',
    status: 'pending',
    lat: 25.461,
    lng: 92.185,
    elevationMeters: 1310,
    description: 'Subgrade subsidence near KM 74 due to torrential seepage. Speed restricted to 20 km/h.',
  },
]

export const INITIAL_PREDICTIONS: DisruptionPrediction[] = [
  {
    segmentId: 'road-nh29-kohima',
    roadCode: 'NH-29-Barail',
    roadName: 'Dimapur – Kohima Barail Pass',
    district: 'Kohima',
    state: 'Nagaland',
    riskLevel: 'high',
    riskProbability: 0.94,
    predictedDisruptionType: 'landslide',
    rainfallIntensityMm: 48,
    forecastRainfall6hMm: 110,
    soilSaturationPercent: 88,
    slopeAngleDeg: 42,
    historicalLandslideIncidents: 19,
    lastComputedAt: '2026-09-18 11:30',
    confidenceScore: 0.92,
  },
  {
    segmentId: 'road-nh10-gangtok',
    roadCode: 'NH-10-Teesta',
    roadName: 'Sevoke – Gangtok Teesta Valley',
    district: 'East Sikkim',
    state: 'Sikkim',
    riskLevel: 'high',
    riskProbability: 0.81,
    predictedDisruptionType: 'flood',
    rainfallIntensityMm: 38,
    forecastRainfall6hMm: 85,
    soilSaturationPercent: 81,
    slopeAngleDeg: 46,
    historicalLandslideIncidents: 14,
    lastComputedAt: '2026-09-18 11:30',
    confidenceScore: 0.88,
  },
  {
    segmentId: 'road-nh13-tawang',
    roadCode: 'NH-13-Sela',
    roadName: 'Bhalukpong – Tawang Pass',
    district: 'Tawang',
    state: 'Arunachal Pradesh',
    riskLevel: 'high',
    riskProbability: 0.73,
    predictedDisruptionType: 'landslide',
    rainfallIntensityMm: 22,
    forecastRainfall6hMm: 55,
    soilSaturationPercent: 65,
    slopeAngleDeg: 48,
    historicalLandslideIncidents: 11,
    lastComputedAt: '2026-09-18 11:30',
    confidenceScore: 0.85,
  },
  {
    segmentId: 'road-nh6-jowai',
    roadCode: 'NH-06-Megh',
    roadName: 'Shillong – Jowai Ridge',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    riskLevel: 'medium',
    riskProbability: 0.65,
    predictedDisruptionType: 'road_damage',
    rainfallIntensityMm: 32,
    forecastRainfall6hMm: 68,
    soilSaturationPercent: 76,
    slopeAngleDeg: 34,
    historicalLandslideIncidents: 8,
    lastComputedAt: '2026-09-18 11:30',
    confidenceScore: 0.84,
  },
  {
    segmentId: 'road-nh306-aizawl',
    roadCode: 'NH-306-Vairangte',
    roadName: 'Silchar – Vairangte Corridor',
    district: 'Aizawl',
    state: 'Mizoram',
    riskLevel: 'low',
    riskProbability: 0.28,
    predictedDisruptionType: 'cleared',
    rainfallIntensityMm: 14,
    forecastRainfall6hMm: 25,
    soilSaturationPercent: 54,
    slopeAngleDeg: 28,
    historicalLandslideIncidents: 4,
    lastComputedAt: '2026-09-18 11:30',
    confidenceScore: 0.9,
  },
  {
    segmentId: 'road-nh27-kamrup',
    roadCode: 'NH-27-SecA',
    roadName: 'Guwahati – Nagaon Plains',
    district: 'Kamrup Metro',
    state: 'Assam',
    riskLevel: 'low',
    riskProbability: 0.14,
    predictedDisruptionType: 'cleared',
    rainfallIntensityMm: 6,
    forecastRainfall6hMm: 12,
    soilSaturationPercent: 42,
    slopeAngleDeg: 8,
    historicalLandslideIncidents: 1,
    lastComputedAt: '2026-09-18 11:30',
    confidenceScore: 0.95,
  },
]

export const INITIAL_ALERTS: AlertNotification[] = [
  {
    id: 'alt-01',
    timestamp: '2026-09-18 09:00',
    district: 'Kohima',
    title: 'CRITICAL: NH-29 Barail Pass Blocked',
    message: 'Heavy landslide confirmed at KM 42. Both lanes impassable. Essential goods carriers reroute immediately via Wokha bypass.',
    severity: 'critical',
    channels: ['in_app', 'sms', 'push'],
    isRead: false,
    isResolved: false,
    relatedRoadCode: 'NH-29-Barail',
  },
  {
    id: 'alt-02',
    timestamp: '2026-09-18 08:15',
    district: 'East Sikkim',
    title: 'WARNING: Teesta Valley Flash-Flood Advisory',
    message: 'NH-10 near Singtam water levels at danger mark. Heavy vehicles halted. Single-lane light traffic under caution.',
    severity: 'warning',
    channels: ['in_app', 'sms'],
    isRead: false,
    isResolved: false,
    relatedRoadCode: 'NH-10-Teesta',
  },
  {
    id: 'alt-03',
    timestamp: '2026-09-18 10:20',
    district: 'East Khasi Hills',
    title: 'ADVISORY: Heavy Monsoon Downpour on NH-6',
    message: 'Predicted 68mm rainfall over next 6 hours. High risk of mudflows between Jowai and Ratacherra.',
    severity: 'info',
    channels: ['in_app'],
    isRead: true,
    isResolved: false,
    relatedRoadCode: 'NH-06-Megh',
  },
]

export const PRECONFIGURED_ROUTES: Record<string, RouteOption[]> = {
  'Guwahati to Kohima': [
    {
      id: 'rt-safest-ghy-koh',
      title: 'AI Safest Alternate Route (via Wokha – Niuland Bypass)',
      distanceKm: 345,
      durationHours: 8.5,
      delayMinutes: 35,
      riskLevel: 'low',
      corridorDescription: 'Bypasses the blocked Barail rockfall zone via NH-29A & Niuland ridge road. Risk weighted score: 22/100.',
      isSafestAI: true,
      isFastestUnrestricted: false,
      pathRoadCodes: ['NH-27-SecA', 'NH-29A-Bypass', 'SH-3-Niuland'],
      waypoints: ['Guwahati', 'Nagaon', 'Golaghat', 'Niuland', 'Kohima North'],
      segments: [
        { roadCode: 'NH-27-SecA', name: 'Guwahati - Nagaon Plains', status: 'open', riskScore: 18, distanceKm: 122 },
        { roadCode: 'NH-29A-Bypass', name: 'Nagaon - Golaghat Link', status: 'open', riskScore: 24, distanceKm: 115 },
        { roadCode: 'SH-3-Niuland', name: 'Niuland Ridge Approach', status: 'open', riskScore: 28, distanceKm: 108 },
      ],
    },
    {
      id: 'rt-fastest-ghy-koh',
      title: 'Fastest Direct Route (NH-29 Barail Pass) — CURRENTLY BLOCKED',
      distanceKm: 295,
      durationHours: 6.2,
      delayMinutes: 240,
      riskLevel: 'high',
      corridorDescription: 'Direct route through Chumoukedima – Barail Pass. Contains active 65m landslide barrier at KM-42.',
      isSafestAI: false,
      isFastestUnrestricted: true,
      pathRoadCodes: ['NH-27-SecA', 'NH-29-Barail'],
      waypoints: ['Guwahati', 'Nagaon', 'Dimapur', 'Barail Pass (BLOCKED)', 'Kohima Gate'],
      segments: [
        { roadCode: 'NH-27-SecA', name: 'Guwahati - Nagaon Plains', status: 'open', riskScore: 18, distanceKm: 122 },
        { roadCode: 'NH-29-Barail', name: 'Dimapur - Kohima Barail Pass', status: 'blocked', riskScore: 92, distanceKm: 173 },
      ],
    },
  ],
  'Siliguri to Gangtok': [
    {
      id: 'rt-safest-slg-gtx',
      title: 'AI Safest Alternate Route (via Lava – Reshi – Rhenock)',
      distanceKm: 148,
      durationHours: 5.4,
      delayMinutes: 40,
      riskLevel: 'medium',
      corridorDescription: 'Avoids Teesta River water level breaches by ascending through Kalimpong-Lava-Rhenock eastern bypass.',
      isSafestAI: true,
      isFastestUnrestricted: false,
      pathRoadCodes: ['NH-717A', 'SH-Lava-Pass', 'Singtam-Link'],
      waypoints: ['Siliguri', 'Gorubathan', 'Lava', 'Rhenock', 'Gangtok East'],
      segments: [
        { roadCode: 'NH-717A', name: 'Siliguri - Gorubathan High Way', status: 'open', riskScore: 26, distanceKm: 58 },
        { roadCode: 'SH-Lava-Pass', name: 'Lava - Rhenock Ridge Road', status: 'open', riskScore: 35, distanceKm: 52 },
        { roadCode: 'Singtam-Link', name: 'Ranipool - Gangtok Approach', status: 'at_risk', riskScore: 48, distanceKm: 38 },
      ],
    },
    {
      id: 'rt-fastest-slg-gtx',
      title: 'Standard Route (NH-10 Sevoke – Singtam) — HIGH WATER LEVEL RISK',
      distanceKm: 114,
      durationHours: 3.8,
      delayMinutes: 90,
      riskLevel: 'high',
      corridorDescription: 'Along Teesta gorge. Experiencing 38mm/hr downpour and river crest alert near 29th Mile.',
      isSafestAI: false,
      isFastestUnrestricted: true,
      pathRoadCodes: ['NH-10-Teesta'],
      waypoints: ['Siliguri', 'Sevoke', 'Kalijhora', 'Singtam', 'Gangtok'],
      segments: [
        { roadCode: 'NH-10-Teesta', name: 'Sevoke - Gangtok Teesta Gorge', status: 'at_risk', riskScore: 74, distanceKm: 114 },
      ],
    },
  ],
  'Guwahati to Silchar': [
    {
      id: 'rt-safest-ghy-sil',
      title: 'AI Safest Alternate Route (via Lumding – Halflong – Harangajao)',
      distanceKm: 335,
      durationHours: 8.0,
      delayMinutes: 20,
      riskLevel: 'low',
      corridorDescription: 'Smooth 4-lane expressway and newly reinforced Dima Hasao viaducts with zero active blockages.',
      isSafestAI: true,
      isFastestUnrestricted: true,
      pathRoadCodes: ['NH-27-EastWest'],
      waypoints: ['Guwahati', 'Nagaon', 'Daboka', 'Halflong', 'Silchar'],
      segments: [
        { roadCode: 'NH-27-EastWest', name: 'Guwahati - Halflong - Silchar Expressway', status: 'open', riskScore: 22, distanceKm: 335 },
      ],
    },
    {
      id: 'rt-alt-ghy-sil-jowai',
      title: 'Alternate Route (via Shillong – Jowai NH-6) — ROAD SUBSIDENCE AT RISK',
      distanceKm: 310,
      durationHours: 8.8,
      delayMinutes: 75,
      riskLevel: 'medium',
      corridorDescription: 'Traverses East Khasi Hills and Jaintia Hills. Active road slump at KM 74 with monsoon caution.',
      isSafestAI: false,
      isFastestUnrestricted: false,
      pathRoadCodes: ['NH-40', 'NH-06-Megh'],
      waypoints: ['Guwahati', 'Shillong', 'Jowai', 'Ratacherra', 'Silchar'],
      segments: [
        { roadCode: 'NH-40', name: 'Guwahati - Shillong 4-Lane', status: 'open', riskScore: 20, distanceKm: 100 },
        { roadCode: 'NH-06-Megh', name: 'Shillong - Jowai - Ratacherra', status: 'at_risk', riskScore: 68, distanceKm: 210 },
      ],
    },
  ],
}
