import {
  AssessmentQuestion,
  BookRecommendation,
  Topic,
  Achievement,
  TopicQuiz,
  ResourceItem,
} from '@/types/quantify'

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  // 1. Basics (2 Questions)
  {
    id: 'q-basic-1',
    category: 'basics',
    difficulty: 'beginner',
    questionText:
      'What is the fundamental unit of quantum information, analogous to the classical binary bit?',
    options: [
      { id: 'opt-b1-a', text: 'Qubit (Quantum Bit)', isCorrect: true },
      { id: 'opt-b1-b', text: 'Quantum Byte', isCorrect: false },
      { id: 'opt-b1-c', text: 'Phonon State', isCorrect: false },
      { id: 'opt-b1-d', text: 'Binary Q-point', isCorrect: false },
    ],
    explanation:
      'A qubit is the fundamental basic unit of quantum information that can exist in a superposition of |0⟩ and |1⟩ states simultaneously.',
  },
  {
    id: 'q-basic-2',
    category: 'basics',
    difficulty: 'beginner',
    questionText:
      'According to quantum mechanics, what occurs to a qubit state vector upon measurement in the computational basis?',
    options: [
      { id: 'opt-b2-a', text: 'It doubles its probability amplitude', isCorrect: false },
      { id: 'opt-b2-b', text: 'It collapses irreversibly to either |0⟩ or |1⟩', isCorrect: true },
      { id: 'opt-b2-c', text: 'It rotates continuously around the Bloch sphere', isCorrect: false },
      { id: 'opt-b2-d', text: 'It creates an exact duplicate copy of itself', isCorrect: false },
    ],
    explanation:
      'The Born rule states that upon measurement, the state vector collapses probabilistically to one of the eigenstates of the measurement observable.',
  },

  // 2. Qubits & Superposition (2 Questions)
  {
    id: 'q-qubit-1',
    category: 'qubits',
    difficulty: 'intermediate',
    questionText:
      'For a normalized qubit state |ψ⟩ = α|0⟩ + β|1⟩, what fundamental mathematical constraint must complex coefficients α and β satisfy?',
    options: [
      { id: 'opt-q1-a', text: '|α| + |β| = 1', isCorrect: false },
      { id: 'opt-q1-b', text: '|α|² + |β|² = 1', isCorrect: true },
      { id: 'opt-q1-c', text: 'α · β = 0', isCorrect: false },
      { id: 'opt-q1-d', text: '|α|² · |β|² = 1/2', isCorrect: false },
    ],
    explanation:
      'Normalization requires total probability conservation: P(0) + P(1) = |α|² + |β|² = 1.',
  },
  {
    id: 'q-qubit-2',
    category: 'qubits',
    difficulty: 'intermediate',
    questionText:
      'Which geometric representation maps single-qubit pure states onto the surface of a unit sphere in 3D space?',
    options: [
      { id: 'opt-q2-a', text: 'Poincaré Disc', isCorrect: false },
      { id: 'opt-q2-b', text: 'Bloch Sphere', isCorrect: true },
      { id: 'opt-q2-c', text: 'Riemann Hyperboloid', isCorrect: false },
      { id: 'opt-q2-d', text: 'Hilbert Torus', isCorrect: false },
    ],
    explanation:
      'The Bloch sphere represents single-qubit pure states parameterized by angles θ and φ as |ψ⟩ = cos(θ/2)|0⟩ + e^(iφ)sin(θ/2)|1⟩.',
  },

  // 3. Gates (2 Questions)
  {
    id: 'q-gate-1',
    category: 'gates',
    difficulty: 'beginner',
    questionText:
      'Which single-qubit quantum gate transforms basis state |0⟩ into equal superposition (|0⟩ + |1⟩)/√2?',
    options: [
      { id: 'opt-g1-a', text: 'Pauli-X Gate', isCorrect: false },
      { id: 'opt-g1-b', text: 'Hadamard (H) Gate', isCorrect: true },
      { id: 'opt-g1-c', text: 'Phase (S) Gate', isCorrect: false },
      { id: 'opt-g1-d', text: 'T Gate (π/8 gate)', isCorrect: false },
    ],
    explanation:
      'The Hadamard gate creates an equal superposition: H|0⟩ = |+⟩ = (|0⟩ + |1⟩)/√2 and H|1⟩ = |-⟩ = (|0⟩ - |1⟩)/√2.',
  },
  {
    id: 'q-gate-2',
    category: 'gates',
    difficulty: 'intermediate',
    questionText:
      'What algebraic property must all quantum gate matrices U satisfy to ensure reversible quantum evolution?',
    options: [
      { id: 'opt-g2-a', text: 'U must be Singular (det(U) = 0)', isCorrect: false },
      { id: 'opt-g2-b', text: 'U must be Unitary (U† U = I)', isCorrect: true },
      { id: 'opt-g2-c', text: 'U must be Skew-symmetric', isCorrect: false },
      { id: 'opt-g2-d', text: 'U must have integer eigenvalues only', isCorrect: false },
    ],
    explanation:
      'Quantum operations are reversible and norm-preserving, which requires the gate matrix to be unitary (U conjugate transpose equals U inverse).',
  },

  // 4. Circuits (2 Questions)
  {
    id: 'q-circ-1',
    category: 'circuits',
    difficulty: 'intermediate',
    questionText:
      'What output state is generated when a 2-qubit register initialized to |00⟩ passes through an H gate on qubit 0 followed by a CNOT (control: q0, target: q1)?',
    options: [
      { id: 'opt-c1-a', text: 'Uncorrelated state |01⟩', isCorrect: false },
      { id: 'opt-c1-b', text: 'Maximal Bell State (|00⟩ + |11⟩)/√2', isCorrect: true },
      { id: 'opt-c1-c', text: 'Equal superposition of all four states', isCorrect: false },
      { id: 'opt-c1-d', text: 'Inverted state |10⟩', isCorrect: false },
    ],
    explanation:
      'H on q0 creates (|0⟩+|1⟩)|0⟩/√2 = (|00⟩+|10⟩)/√2. CNOT with q0 as control flips q1 when q0 is 1, yielding (|00⟩ + |11⟩)/√2 (Bell state Φ+).',
  },
  {
    id: 'q-circ-2',
    category: 'circuits',
    difficulty: 'advanced',
    questionText:
      'According to the No-Cloning Theorem in quantum circuit theory, what operation is physically impossible?',
    options: [
      { id: 'opt-c2-a', text: 'Teleporting quantum state information via entanglement', isCorrect: false },
      { id: 'opt-c2-b', text: 'Creating an identical copy of an arbitrary unknown quantum state', isCorrect: true },
      { id: 'opt-c2-c', text: 'Entangling more than two qubits simultaneously', isCorrect: false },
      { id: 'opt-c2-d', text: 'Simulating quantum gates on a classical computer', isCorrect: false },
    ],
    explanation:
      'The No-Cloning theorem proves that linearity of quantum mechanics prohibits the creation of an identical copy of an arbitrary unknown quantum state.',
  },

  // 5. Algorithms (2 Questions)
  {
    id: 'q-algo-1',
    category: 'algorithms',
    difficulty: 'intermediate',
    questionText:
      'Which quantum algorithm provides an exponential speedup for factoring large composite integers into primes?',
    options: [
      { id: 'opt-a1-a', text: "Grover's Search Algorithm", isCorrect: false },
      { id: 'opt-a1-b', text: "Shor's Factoring Algorithm", isCorrect: true },
      { id: 'opt-a1-c', text: 'Deutsch-Jozsa Algorithm', isCorrect: false },
      { id: 'opt-a1-d', text: 'Quantum Counting', isCorrect: false },
    ],
    explanation:
      "Shor's algorithm achieves polynomial time O((log N)³) for integer factorization using the Quantum Fourier Transform, yielding an exponential speedup over classical algorithms.",
  },
  {
    id: 'q-algo-2',
    category: 'algorithms',
    difficulty: 'advanced',
    questionText:
      "What quadratic speedup does Grover's search algorithm achieve over classical brute force search on an unsorted database of N items?",
    options: [
      { id: 'opt-a2-a', text: 'O(log N) compared to O(N)', isCorrect: false },
      { id: 'opt-a2-b', text: 'O(√N) queries compared to O(N) classical queries', isCorrect: true },
      { id: 'opt-a2-c', text: 'O(1) constant time queries', isCorrect: false },
      { id: 'opt-a2-d', text: 'O(N²) queries', isCorrect: false },
    ],
    explanation:
      "Grover's algorithm uses amplitude amplification to locate the marked target element in O(√N) oracle evaluations, a quadratic speedup over classical O(N).",
  },
]

export const CURRICULUM_TOPICS: Topic[] = [
  // Beginner Track (Section 13)
  {
    id: 'topic-intro',
    category: 'basics',
    name: 'Introduction to Quantum Computing',
    level: 'beginner',
    sequenceOrder: 1,
    description: 'Foundations of quantum mechanics, classical vs quantum bits, and computational paradigms.',
    theoryContent: `Quantum computing leverages physical principles of quantum mechanics—such as superposition, interference, and entanglement—to process information in fundamentally distinct ways from classical computing. While a classical bit is strictly 0 or 1, a qubit exists in a continuous vector space represented as |ψ⟩ = α|0⟩ + β|1⟩.`,
    videoUrl: 'https://www.youtube.com/embed/QuR969uMICM',
    videoDuration: '14 mins',
    notesUrl: '#',
    practiceQuestionsCount: 4,
    keyFormulas: ['|ψ⟩ = α|0⟩ + β|1⟩', '|α|² + |β|² = 1'],
  },
  {
    id: 'topic-qubits',
    category: 'qubits',
    name: 'Qubits & Bloch Sphere Geometry',
    level: 'beginner',
    sequenceOrder: 2,
    description: 'Mathematical representation of 2-level quantum systems and the geometric Bloch sphere.',
    theoryContent: `Any pure single-qubit state can be visualized as a point on the unit 3D sphere known as the Bloch Sphere. Angles θ (polar) and φ (azimuthal) define the state vector: |ψ⟩ = cos(θ/2)|0⟩ + e^(iφ)sin(θ/2)|1⟩. Rotations around the X, Y, and Z axes correspond to unitary operations.`,
    videoUrl: 'https://www.youtube.com/embed/6iOmsv5gY5E',
    videoDuration: '18 mins',
    notesUrl: '#',
    practiceQuestionsCount: 5,
    keyFormulas: ['|ψ⟩ = cos(θ/2)|0⟩ + e^(iφ)sin(θ/2)|1⟩', 'θ ∈ [0, π], φ ∈ [0, 2π)'],
  },
  {
    id: 'topic-gates',
    category: 'gates',
    name: 'Single-Qubit Quantum Gates',
    level: 'beginner',
    sequenceOrder: 3,
    description: 'Pauli matrices (X, Y, Z), Hadamard gate, and phase rotation operators (S, T).',
    theoryContent: `Quantum gates are represented by unitary matrices U where U†U = I. The Pauli-X gate flips states (|0⟩ ↔ |1⟩). The Hadamard (H) gate creates balanced superposition: H = 1/√2 [[1, 1], [1, -1]]. S and T gates introduce phase rotations of π/2 and π/4 respectively.`,
    videoUrl: 'https://www.youtube.com/embed/F_Riqjdh2oM',
    videoDuration: '22 mins',
    notesUrl: '#',
    practiceQuestionsCount: 6,
    keyFormulas: ['X = [[0, 1], [1, 0]]', 'H = 1/√2 [[1, 1], [1, -1]]', 'T = [[1, 0], [0, e^(iπ/4)]]'],
  },
  {
    id: 'topic-circuits',
    category: 'circuits',
    name: 'Quantum Circuits & Measurement',
    level: 'beginner',
    sequenceOrder: 4,
    description: 'Reading quantum circuit diagrams, wire registers, gate sequences, and projective measurement.',
    theoryContent: `A quantum circuit is a model where computation proceeds along horizontal qubit wires through discrete time steps. Applying sequential gates corresponds to matrix multiplication from right to left: U_total = U_k ··· U_2 U_1. Measurement collapses the wave function according to the Born rule.`,
    videoUrl: 'https://www.youtube.com/embed/m7wO1i4e20g',
    videoDuration: '16 mins',
    notesUrl: '#',
    practiceQuestionsCount: 5,
    keyFormulas: ['P(m) = |⟨m|ψ⟩|²', 'U_total = U_2 · U_1'],
  },
  {
    id: 'topic-entanglement',
    category: 'circuits',
    name: 'Entanglement & Bell States',
    level: 'intermediate',
    sequenceOrder: 5,
    description: 'Non-separable 2-qubit states, EPR paradox, and constructing Bell basis states.',
    theoryContent: `Quantum entanglement occurs when multi-qubit states cannot be factored into tensor products of individual qubit states: |ψ⟩ ≠ |q1⟩ ⊗ |q2⟩. The four canonical Bell states (|Φ+⟩, |Φ-⟩, |Ψ+⟩, |Ψ-⟩) form a complete orthonormal basis for 2-qubit systems.`,
    videoUrl: 'https://www.youtube.com/embed/0RiAXL2tLqQ',
    videoDuration: '24 mins',
    notesUrl: '#',
    practiceQuestionsCount: 6,
    keyFormulas: ['|Φ+⟩ = (|00⟩ + |11⟩)/√2', '|Ψ+⟩ = (|01⟩ + |10⟩)/√2'],
  },

  // Intermediate Track (Section 13)
  {
    id: 'topic-teleportation',
    category: 'algorithms',
    name: 'Quantum Teleportation Protocol',
    level: 'intermediate',
    sequenceOrder: 6,
    description: 'Transmitting an arbitrary unknown quantum state using shared entanglement and classical bits.',
    theoryContent: `Quantum teleportation allows Alice to transmit an unknown qubit state |ψ⟩ to Bob without physically sending the particle. By utilizing a shared Bell pair and sending two classical measurement outcomes, Bob can apply Pauli corrections (I, X, Z, or XZ) to reconstruct |ψ⟩ perfectly.`,
    videoUrl: 'https://www.youtube.com/embed/DxQK1WDYI_k',
    videoDuration: '28 mins',
    notesUrl: '#',
    practiceQuestionsCount: 4,
    keyFormulas: ['EPR Pair + 2 Classical Bits → 1 Qubit Teleported'],
  },
  {
    id: 'topic-deutsch',
    category: 'algorithms',
    name: 'Deutsch-Jozsa Algorithm',
    level: 'intermediate',
    sequenceOrder: 7,
    description: 'The canonical algorithm demonstrating deterministic exponential speedup over classical oracle queries.',
    theoryContent: `Determines whether a boolean oracle function f: {0,1}^n → {0,1} is constant (same output for all inputs) or balanced (equal 0s and 1s). While classical deterministic algorithms require up to 2^(n-1) + 1 evaluations, Deutsch-Jozsa requires exactly ONE quantum oracle evaluation.`,
    videoUrl: 'https://www.youtube.com/embed/5xsyx-fcVYs',
    videoDuration: '25 mins',
    notesUrl: '#',
    practiceQuestionsCount: 5,
    keyFormulas: ['Quantum: 1 query vs Classical: 2^(n-1) + 1 queries'],
  },
  {
    id: 'topic-grover',
    category: 'algorithms',
    name: "Grover's Search Algorithm",
    level: 'intermediate',
    sequenceOrder: 8,
    description: 'Amplitude amplification technique providing a quadratic speedup for unstructured database search.',
    theoryContent: `Grover's algorithm searches an unsorted database of N = 2^n elements in O(√N) iterations. It works by alternating between phase inversion of the target state (Oracle) and reflection about the mean amplitude (Diffusion operator), progressively boosting the probability of measuring the correct answer.`,
    videoUrl: 'https://www.youtube.com/embed/IT-O-IEFeQE',
    videoDuration: '32 mins',
    notesUrl: '#',
    practiceQuestionsCount: 7,
    keyFormulas: ['Iterations ≈ (π/4)√N', 'D = 2|s⟩⟨s| - I'],
  },

  // Advanced Track (Section 13)
  {
    id: 'topic-qft',
    category: 'algorithms',
    name: 'Quantum Fourier Transform (QFT)',
    level: 'advanced',
    sequenceOrder: 9,
    description: 'Quantum analog of the discrete Fourier transform and backbone of Shor’s algorithm.',
    theoryContent: `The QFT transforms computational basis states into phase-frequency basis states: |j⟩ → 1/√N ∑ e^(2πi jk/N) |k⟩. It runs in O(n²) quantum gates, exponentially faster than the classical Fast Fourier Transform (FFT) which takes O(n · 2^n) operations.`,
    videoUrl: 'https://www.youtube.com/embed/mGkK_H5V3aE',
    videoDuration: '36 mins',
    notesUrl: '#',
    practiceQuestionsCount: 6,
    keyFormulas: ['|j⟩ → 1/√N ∑_(k=0)^(N-1) ω^(jk) |k⟩', 'Circuit Depth: O(n²)'],
  },
  {
    id: 'topic-shor',
    category: 'algorithms',
    name: "Shor's Factoring Algorithm",
    level: 'advanced',
    sequenceOrder: 10,
    description: 'Polynomial-time prime factorization of composite numbers using quantum phase estimation.',
    theoryContent: `Shor's algorithm reduces integer factorization to order finding: finding the period r of f(x) = a^x mod N. The Quantum Phase Estimation (QPE) routine combined with continued fractions finds r in polynomial time O((log N)³), rendering classical RSA encryption vulnerable.`,
    videoUrl: 'https://www.youtube.com/embed/lvTqbM5Dq4Q',
    videoDuration: '40 mins',
    notesUrl: '#',
    practiceQuestionsCount: 8,
    keyFormulas: ['Periodicity: a^r ≡ 1 (mod N)', 'gcd(a^(r/2) ± 1, N)'],
  },
]

// Curated Real Books (FR-BOOK-001..004, no fabricated titles/authors)
export const CURATED_BOOKS: BookRecommendation[] = [
  {
    id: 'book-nielsen-chuang',
    title: 'Quantum Computation and Quantum Information',
    author: 'Michael A. Nielsen & Isaac L. Chuang',
    levelTag: 'advanced',
    relatedCategory: 'algorithms',
    coverImage: '/images/student-cosmos.png',
    whyRecommended: 'The gold-standard bible of quantum computing. Recommended to master formal mathematical proofs and quantum algorithms.',
    isbn: '978-1107002173',
    bookmarked: true,
  },
  {
    id: 'book-bernhardt',
    title: 'Quantum Computing for Everyone',
    author: 'Chris Bernhardt (MIT Press)',
    levelTag: 'beginner',
    relatedCategory: 'basics',
    coverImage: '/images/quantum-orb.png',
    whyRecommended: 'Recommended because your assessment identified fundamental quantum principles as a priority area.',
    isbn: '978-0262539531',
    bookmarked: false,
  },
  {
    id: 'book-wong',
    title: 'Introduction to Classical and Quantum Computing',
    author: 'Thomas G. Wong',
    levelTag: 'beginner',
    relatedCategory: 'gates',
    coverImage: '/images/quantum-nebula.png',
    whyRecommended: 'Recommended because your Quantum Gates score was low. Provides crystal-clear matrix step-by-step walkthroughs.',
    isbn: '978-1737025207',
    bookmarked: true,
  },
  {
    id: 'book-kaye',
    title: 'An Introduction to Quantum Computing',
    author: 'Phillip Kaye, Raymond Laflamme & Michele Mosca',
    levelTag: 'intermediate',
    relatedCategory: 'circuits',
    coverImage: '/images/quantum-orb.png',
    whyRecommended: 'Recommended for intermediate learners to master 2-qubit circuit decomposition, Bell states, and phase estimation.',
    isbn: '978-0198570493',
    bookmarked: false,
  },
  {
    id: 'book-svore',
    title: 'Quantum Computer Systems: Research for Noisy Intermediate-Scale Quantum and Beyond',
    author: 'Yongshan Ding & Frederic T. Chong',
    levelTag: 'advanced',
    relatedCategory: 'algorithms',
    coverImage: '/images/student-cosmos.png',
    whyRecommended: 'Recommended to explore NISQ architectures, error mitigation, and hybrid variational quantum algorithms.',
    isbn: '978-3031023798',
    bookmarked: false,
  },
]

export const TOPIC_QUIZZES: Record<string, TopicQuiz> = {
  'topic-intro': {
    topicId: 'topic-intro',
    topicName: 'Introduction to Quantum Computing',
    questions: [
      {
        id: 'quiz-intro-1',
        questionText: 'Which physical principle allows a qubit to be in a linear combination of states |0⟩ and |1⟩?',
        options: [
          { id: 'o1', text: 'Quantum Superposition', isCorrect: true },
          { id: 'o2', text: 'Thermal Dissipation', isCorrect: false },
          { id: 'o3', text: 'Classical Parity', isCorrect: false },
        ],
        explanation: 'Superposition enables qubits to exist in continuous linear combinations of basis states.',
      },
      {
        id: 'quiz-intro-2',
        questionText: 'What is the sum of probability amplitudes squared for a normalized qubit state?',
        options: [
          { id: 'o1', text: '0.5', isCorrect: false },
          { id: 'o2', text: '1.0', isCorrect: true },
          { id: 'o3', text: '2.0', isCorrect: false },
        ],
        explanation: 'Normalization requires |α|² + |β|² = 1 for total probability conservation.',
      },
    ],
  },
  'topic-gates': {
    topicId: 'topic-gates',
    topicName: 'Single-Qubit Quantum Gates',
    questions: [
      {
        id: 'quiz-gates-1',
        questionText: 'What is the result of applying a Hadamard gate to state |1⟩?',
        options: [
          { id: 'o1', text: '(|0⟩ - |1⟩)/√2', isCorrect: true },
          { id: 'o2', text: '(|0⟩ + |1⟩)/√2', isCorrect: false },
          { id: 'o3', text: '|0⟩', isCorrect: false },
        ],
        explanation: 'H|1⟩ = |-⟩ = (|0⟩ - |1⟩)/√2.',
      },
      {
        id: 'quiz-gates-2',
        questionText: 'Which Pauli gate maps |0⟩ to |1⟩ and |1⟩ to |0⟩?',
        options: [
          { id: 'o1', text: 'Pauli-X (NOT gate)', isCorrect: true },
          { id: 'o2', text: 'Pauli-Z gate', isCorrect: false },
          { id: 'o3', text: 'Phase-S gate', isCorrect: false },
        ],
        explanation: 'The Pauli-X gate acts as the quantum bit-flip NOT operator.',
      },
    ],
  },
}

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    title: 'Quantum Diagnostics Complete',
    description: 'Completed the 10-question baseline diagnostic assessment.',
    icon: '🎯',
    isEarned: true,
    earnedAt: '2026-09-18',
    progress: 100,
  },
  {
    id: 'ach-2',
    title: 'Superposition Pioneer',
    description: 'Created your first single-qubit equal superposition state using H gate.',
    icon: '⚡',
    isEarned: true,
    earnedAt: '2026-09-18',
    progress: 100,
  },
  {
    id: 'ach-3',
    title: 'Bell State Architect',
    description: 'Successfully simulated a 2-qubit maximally entangled Bell pair (H + CNOT).',
    icon: '🔗',
    isEarned: false,
    progress: 50,
  },
  {
    id: 'ach-4',
    title: 'Quanta AI Scholar',
    description: 'Asked 5 context-grounded quantum algorithm questions to Quanta AI.',
    icon: '🤖',
    isEarned: false,
    progress: 40,
  },
  {
    id: 'ach-5',
    title: '7-Day Quantum Streak',
    description: 'Completed consecutive daily quantum study modules for 7 days.',
    icon: '🔥',
    isEarned: false,
    progress: 71,
  },
]

export const RESOURCE_LIBRARY_ITEMS: ResourceItem[] = [
  {
    id: 'res-1',
    title: 'Visualizing Qubits and the Bloch Sphere',
    type: 'video',
    topicId: 'topic-qubits',
    topicName: 'Qubits & Bloch Sphere Geometry',
    level: 'beginner',
    url: 'https://www.youtube.com/embed/6iOmsv5gY5E',
    durationOrPages: '18 mins',
    description: '3D interactive walkthrough of pure state vectors, polar and azimuthal angle parameterization.',
  },
  {
    id: 'res-2',
    title: 'Single-Qubit Unitary Operators & Pauli Matrices',
    type: 'notes',
    topicId: 'topic-gates',
    topicName: 'Single-Qubit Quantum Gates',
    level: 'beginner',
    url: '#',
    durationOrPages: '12 pages PDF',
    description: 'Matrix decompositions, eigenvalues, and phase rotation derivations for X, Y, Z, H, S, and T gates.',
  },
  {
    id: 'res-3',
    title: 'Bell State Synthesis and Entanglement Verification',
    type: 'practice',
    topicId: 'topic-entanglement',
    topicName: 'Entanglement & Bell States',
    level: 'intermediate',
    url: '#',
    durationOrPages: '6 interactive circuits',
    description: 'Hands-on practice constructing Phi+, Phi-, Psi+, and Psi- Bell states and checking correlated measurement statistics.',
  },
  {
    id: 'res-4',
    title: "Quantum Oracle Construction for Grover's Algorithm",
    type: 'article',
    topicId: 'topic-grover',
    topicName: "Grover's Search Algorithm",
    level: 'intermediate',
    url: '#',
    durationOrPages: '15 mins read',
    description: 'Step-by-step phase inversion oracles and amplitude diffusion operators for unstructured database searches.',
  },
  {
    id: 'res-5',
    title: "Qiskit Aer Documentation: Classical State-Vector Simulation",
    type: 'documentation',
    topicId: 'topic-circuits',
    topicName: 'Quantum Circuits & Measurement',
    level: 'intermediate',
    url: '#',
    durationOrPages: 'Official API Guide',
    description: 'Reference guide on state-vector simulation, measurement counts, shots, and density matrices.',
  },
  {
    id: 'res-6',
    title: "Quantum Phase Estimation and Order Finding in Shor's Algorithm",
    type: 'notes',
    topicId: 'topic-shor',
    topicName: "Shor's Factoring Algorithm",
    level: 'advanced',
    url: '#',
    durationOrPages: '24 pages PDF',
    description: 'Mathematical reduction of factoring to period finding, continued fractions algorithm, and complexity bounds.',
  },
  {
    id: 'res-7',
    title: 'Qiskit — From Zero to Quantum',
    type: 'video',
    topicId: 'topic-qubits',
    topicName: 'Quantum Fundamentals & Qiskit',
    level: 'beginner',
    url: 'https://www.youtube.com/playlist?list=PLOFEBzvs-VvrXTMy5Y2IqmSaUjfnhvBHR',
    durationOrPages: 'Video Playlist',
    description: 'Complete video tutorial series covering quantum computing principles and programming with Qiskit.',
  },
  {
    id: 'res-8',
    title: 'NPTEL - IITM Quantum Computing Series',
    type: 'video',
    topicId: 'topic-grover',
    topicName: 'Quantum Algorithms & Information',
    level: 'intermediate',
    url: 'https://www.youtube.com/playlist?list=PLuBwWyD3M82x9PfxeF7oxb0E122mQAWh6',
    durationOrPages: 'Video Playlist',
    description: 'Comprehensive academic lecture series on quantum algorithms and quantum information from IIT Madras.',
  },
  {
    id: 'res-9',
    title: 'IBM Technology Quantum Series',
    type: 'video',
    topicId: 'topic-qubits',
    topicName: 'Quantum Fundamentals',
    level: 'beginner',
    url: 'https://www.youtube.com/playlist?list=PLOspHqNVtKADPNAxbcP2u6CPzD1g_bBhe',
    durationOrPages: 'Video Playlist',
    description: 'Bite-sized explanatory videos on quantum computing fundamentals, hardware, and applications.',
  },
  {
    id: 'res-10',
    title: 'MIT OpenCourseWare Quantum Lectures',
    type: 'video',
    topicId: 'topic-entanglement',
    topicName: 'Quantum Information',
    level: 'intermediate',
    url: 'https://www.youtube.com/playlist?list=PLUl4u3cNGP61-9PEhRognw5vryrSEVLPr',
    durationOrPages: 'Video Playlist',
    description: 'Lecture video series on quantum computation and quantum mechanics principles from MIT.',
  },
  {
    id: 'res-11',
    title: 'Lecture Notes for Physics 219: Quantum Computation',
    type: 'notes',
    topicId: 'topic-entanglement',
    topicName: 'Quantum Computation',
    level: 'advanced',
    url: 'https://www.researchgate.net/publication/238451035_Lecture_Notes_for_Physics_219_Quantum_Computation',
    durationOrPages: 'Reference Notes',
    description: 'Foundational lecture notes covering quantum states, entanglements, quantum channels, and quantum error correction.',
  },
  {
    id: 'res-12',
    title: 'MIT Quantum Computation Course Notes',
    type: 'notes',
    topicId: 'topic-shor',
    topicName: 'Quantum Algorithms',
    level: 'intermediate',
    url: 'https://ocw.mit.edu/courses/18-435j-quantum-computation-fall-2003/pages/lecture-notes/',
    durationOrPages: 'Course / Notes',
    description: 'Lecture notes, assignments, and reference materials for MIT 18.435J / 2.111J Quantum Computation.',
  },
  {
    id: 'res-13',
    title: 'MIT — Quantum Information Science I',
    type: 'notes',
    topicId: 'topic-qubits',
    topicName: 'Quantum Information',
    level: 'intermediate',
    url: 'https://ocw.mit.edu/courses/8-370x-quantum-information-science-i-spring-2018/?utm_source=chatgpt.com',
    durationOrPages: 'Course Series',
    description: 'Online course materials for MIT 8.370x covering quantum circuits, algorithms, and quantum information processing.',
  },
  {
    id: 'res-14',
    title: 'IBM Quantum — Complete Quantum Information Course Series',
    type: 'documentation',
    topicId: 'topic-qubits',
    topicName: 'Quantum Information',
    level: 'beginner',
    url: 'https://quantum.cloud.ibm.com/learning/en/courses?utm_source=chatgpt.com',
    durationOrPages: 'Course Series',
    description: 'Interactive educational modules and full course series on quantum information science hosted by IBM Quantum.',
  },
  {
    id: 'res-15',
    title: 'TU Delft — Quantum Computing & Information Resources',
    type: 'notes',
    topicId: 'topic-entanglement',
    topicName: 'Quantum Cryptography',
    level: 'intermediate',
    url: 'https://ocw.tudelft.nl/courses/quantum-cryptography/?view=course-materials',
    durationOrPages: 'Course Materials',
    description: 'Open course materials and notes on quantum cryptography, key distribution, and quantum communications from TU Delft.',
  },
  {
    id: 'res-16',
    title: 'University of Tennessee — Quantum Information Resources',
    type: 'documentation',
    topicId: 'topic-qubits',
    topicName: 'Quantum Information',
    level: 'beginner',
    url: 'https://quantum.utk.edu/courses/introduction-to-quantum-information/resources',
    durationOrPages: 'Course Resources',
    description: 'Curated course syllabus, reading lists, and lecture resources for Introduction to Quantum Information.',
  },
]

